"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const offset_category_1 = require("./../../../shared/offset-category");
const offset_1 = require("./../../../shared/offset");
exports.electric = {
    masterBatterySwitch: new offset_1.Offset({
        value: 0x281C,
        name: 'masterBatterySwitch',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'battery master switch',
        convert: '!!{VAL}',
        type: 6 /* UInt32 */,
        permission: 'rw',
    }),
    totalLoadAmp: new offset_1.Offset({
        value: 0x2824,
        name: 'totalLoadAmp',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'total load amps',
        type: 8 /* Double */,
        permission: 'r',
    }),
    batteryLoad: new offset_1.Offset({
        value: 0x282C,
        name: 'batteryLoad',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'battery load',
        type: 8 /* Double */,
        permission: 'r',
    }),
    batteryVoltage: new offset_1.Offset({
        value: 0x2834,
        name: 'batteryVoltage',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'battery voltage',
        type: 8 /* Double */,
        permission: 'r',
    }),
    mainBusVoltage: new offset_1.Offset({
        value: 0x2840,
        name: 'mainBusVoltage',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'main bus voltage',
        type: 8 /* Double */,
        permission: 'r',
    }),
    mainBusAmps: new offset_1.Offset({
        value: 0x2848,
        name: 'mainBusAmps',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'main bus amps',
        type: 8 /* Double */,
        permission: 'r',
    }),
    avionicsBusVoltage: new offset_1.Offset({
        value: 0x2850,
        name: 'avionicsBusVoltage',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'avionics bus voltage',
        type: 8 /* Double */,
        permission: 'r',
    }),
    avionicsBusAmps: new offset_1.Offset({
        value: 0x2858,
        name: 'avionicsBusAmps',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'avionics bus amps',
        type: 8 /* Double */,
        permission: 'r',
    }),
    hotBatteryBusVoltage: new offset_1.Offset({
        value: 0x2860,
        name: 'hotBatteryBusVoltage',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'hot battery bus voltage',
        type: 8 /* Double */,
        permission: 'r',
    }),
    hotBatteryBusAmps: new offset_1.Offset({
        value: 0x2868,
        name: 'hotBatteryBusAmps',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'hot battery bus amps',
        type: 8 /* Double */,
        permission: 'r',
    }),
    batteryBusVoltage: new offset_1.Offset({
        value: 0x2870,
        name: 'batteryBusVoltage',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'battery bus voltage',
        type: 8 /* Double */,
        permission: 'r',
    }),
    batteryBusAmps: new offset_1.Offset({
        value: 0x2878,
        name: 'batteryBusAmps',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'battery bus amps',
        type: 8 /* Double */,
        permission: 'r',
    }),
    generatorAlternator1BusVoltage: new offset_1.Offset({
        value: 0x2880,
        name: 'generatorAlternator1BusVoltage',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'generator alternator 1 bus voltage',
        type: 8 /* Double */,
        permission: 'r',
    }),
    generatorAlternator1BusAmps: new offset_1.Offset({
        value: 0x2888,
        name: 'generatorAlternator1BusAmps',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'generator alternator 1 bus amps',
        type: 8 /* Double */,
        permission: 'r',
    }),
    generatorAlternator2BusVoltage: new offset_1.Offset({
        value: 0x2890,
        name: 'generatorAlternator2BusVoltage',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'generator alternator 2 bus voltage',
        type: 8 /* Double */,
        permission: 'r',
    }),
    generatorAlternator2BusAmps: new offset_1.Offset({
        value: 0x2898,
        name: 'generatorAlternator2BusAmps',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'generator alternator 2 bus amps',
        type: 8 /* Double */,
        permission: 'r',
    }),
    generatorAlternator3BusVoltage: new offset_1.Offset({
        value: 0x28A0,
        name: 'generatorAlternator3BusVoltage',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'generator alternator 3 bus voltage',
        type: 8 /* Double */,
        permission: 'r',
    }),
    generatorAlternator3BusAmps: new offset_1.Offset({
        value: 0x28A8,
        name: 'generatorAlternator3BusAmps',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'generator alternator 3 bus amps',
        type: 8 /* Double */,
        permission: 'r',
    }),
    generatorAlternator4BusVoltage: new offset_1.Offset({
        value: 0x28B0,
        name: 'generatorAlternator4BusVoltage',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'generator alternator 4 bus voltage',
        type: 8 /* Double */,
        permission: 'r',
    }),
    generatorAlternator4BusAmps: new offset_1.Offset({
        value: 0x28B8,
        name: 'generatorAlternator4BusAmps',
        category: offset_category_1.OffsetCategory.ELECTRIC,
        description: 'generator alternator 4 bus amps',
        type: 8 /* Double */,
        permission: 'r',
    }),
};
