"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const offset_category_1 = require("./../../../shared/offset-category");
const offset_1 = require("./../../../shared/offset");
exports.fuel = {
    fuelWeight: new offset_1.Offset({
        value: 0xAF4,
        name: 'fuelWeight',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'fuel weight - lbs/gal',
        type: 2 /* Int16 */,
        convert: '{VAL} / 256',
        permission: 'r',
    }),
    fuelTankSelector: new offset_1.Offset({
        value: 0xAF8,
        name: 'fuelTankSelector',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'Engine 1 only',
        convert: 'fuelTank',
        mapping: true,
        type: 2 /* Int16 */,
        permission: 'rw',
    }),
    fuelCenterTankLevel: new offset_1.Offset({
        value: 0xB74,
        name: 'fuelCenterTankLevel',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'center tank level - percent',
        convert: 'Math.round({VAL} / (128 * 65536) * 100)',
        type: 3 /* Int32 */,
        permission: 'rw',
    }),
    fuelCenterTankCapacity: new offset_1.Offset({
        value: 0xB78,
        name: 'fuelCenterTankCapacity',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'center tank capacity - US gallons',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    fuelLeftMainTankLevel: new offset_1.Offset({
        value: 0xB7C,
        name: 'fuelLeftMainTankLevel',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'left main tank level - percent',
        convert: 'Math.round({VAL} / (128 * 65536) * 100)',
        type: 3 /* Int32 */,
        permission: 'rw',
    }),
    fuelLeftMainTankCapacity: new offset_1.Offset({
        value: 0xB80,
        name: 'fuelLeftMainTankCapacity',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'left main tank capacity - US gallons',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    fuelLeftAuxTankLevel: new offset_1.Offset({
        value: 0xB84,
        name: 'fuelLeftAuxTankLevel',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'left aux tank level - percent',
        convert: 'Math.round({VAL} / (128 * 65536) * 100)',
        type: 3 /* Int32 */,
        permission: 'rw',
    }),
    fuelLeftAuxTankCapacity: new offset_1.Offset({
        value: 0xB88,
        name: 'fuelLeftAuxTankCapacity',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'left aux tank capacity - US gallons',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    fuelLeftTipTankLevel: new offset_1.Offset({
        value: 0xB8C,
        name: 'fuelLeftTipTankLevel',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'left tip tank level - percent',
        convert: 'Math.round({VAL} / (128 * 65536) * 100)',
        type: 3 /* Int32 */,
        permission: 'rw',
    }),
    fuelLeftTipTankCapacity: new offset_1.Offset({
        value: 0xB90,
        name: 'fuelLeftTipTankCapacity',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'left tip tank capacity - US gallons',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    fuelRightMainTankLevel: new offset_1.Offset({
        value: 0xB94,
        name: 'fuelRightMainTankLevel',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'right main tank level - percent',
        convert: 'Math.round({VAL} / (128 * 65536) * 100)',
        type: 3 /* Int32 */,
        permission: 'rw',
    }),
    fuelRightMainTankCapacity: new offset_1.Offset({
        value: 0xB98,
        name: 'fuelRightMainTankCapacity',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'right main tank capacity - US gallons',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    fuelRightAuxTankLevel: new offset_1.Offset({
        value: 0xB9C,
        name: 'fuelRightAuxTankLevel',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'right aux tank level - percent',
        convert: 'Math.round({VAL} / (128 * 65536) * 100)',
        type: 3 /* Int32 */,
        permission: 'rw',
    }),
    fuelRightAuxTankCapacity: new offset_1.Offset({
        value: 0xBA0,
        name: 'fuelRightAuxTankCapacity',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'right aux tank capacity - US gallons',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    fuelRightTipTankLevel: new offset_1.Offset({
        value: 0xBA4,
        name: 'fuelRightTipTankLevel',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'right tip tank level - percent',
        convert: 'Math.round({VAL} / (128 * 65536) * 100)',
        type: 3 /* Int32 */,
        permission: 'rw',
    }),
    fuelRightTipTankCapacity: new offset_1.Offset({
        value: 0xBA8,
        name: 'fuelRightTipTankCapacity',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'right tip tank capacity - US gallons',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    totalFuelCapacity: new offset_1.Offset({
        value: 0x1240,
        name: 'totalFuelCapacity',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'total fuel capacity - US gallons',
        type: 6 /* UInt32 */,
        permission: 'r',
    }),
    fuelCenter2TankLevel: new offset_1.Offset({
        value: 0x1244,
        name: 'fuelCenter2TankLevel',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'center 2 tank level - percent',
        convert: 'Math.round({VAL} / (128 * 65536) * 100)',
        type: 3 /* Int32 */,
        permission: 'rw',
    }),
    fuelCenter2TankCapacity: new offset_1.Offset({
        value: 0x1248,
        name: 'fuelCenter2TankCapacity',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'center 2 tank capacity - US gallons',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    fuelCenter3TankLevel: new offset_1.Offset({
        value: 0x124C,
        name: 'fuelCenter3TankLevel',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'center 3 tank level - percent',
        convert: 'Math.round({VAL} / (128 * 65536) * 100)',
        type: 3 /* Int32 */,
        permission: 'rw',
    }),
    fuelCenter3TankCapacity: new offset_1.Offset({
        value: 0x1250,
        name: 'fuelCenter3TankCapacity',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'center 3 tank capacity - US gallons',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    fuelExternal1TankLevel: new offset_1.Offset({
        value: 0x1254,
        name: 'fuelExternal1TankLevel',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'external 1 tank level - percent',
        convert: 'Math.round({VAL} / (128 * 65536) * 100)',
        type: 3 /* Int32 */,
        permission: 'rw',
    }),
    fuelExternal1TankCapacity: new offset_1.Offset({
        value: 0x1258,
        name: 'fuelExternal1TankCapacity',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'external 1 tank capacity - US gallons',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    fuelExternal2TankLevel: new offset_1.Offset({
        value: 0x125C,
        name: 'fuelExternal2TankLevel',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'external 2 tank level - percent',
        convert: 'Math.round({VAL} / (128 * 65536) * 100)',
        type: 3 /* Int32 */,
        permission: 'rw',
    }),
    fuelExternal2TankCapacity: new offset_1.Offset({
        value: 0x1260,
        name: 'fuelExternal2TankCapacity',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'external 2 tank capacity - US gallons',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    fuelTotalQuantity: new offset_1.Offset({
        value: 0x1264,
        name: 'fuelTotalQuantity',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'total fuel quantity - US gallons',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    fuelSelectedQuantity: new offset_1.Offset({
        value: 0x1268,
        name: 'fuelSelectedQuantity',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'Selected fuel quantity - US gallons',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    fuelTotalQuantityWeight: new offset_1.Offset({
        value: 0x126C,
        name: 'fuelTotalQuantityWeight',
        category: offset_category_1.OffsetCategory.FUEL,
        description: 'total fuel quantity weight - lb',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
};
