"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const offset_1 = require("./../../../../shared/offset");
const offset_category_1 = require("./../../../../shared/offset-category");
exports.engine3 = {
    engine3ThrottleLever: new offset_1.Offset({
        value: 0x9BC,
        name: 'engine3ThrottleLever',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 throttle lever - percent - negative = reverse',
        convert: 'Math.round({VAL} < 0 ? {VAL} / 4096 * 100 : {VAL} / 16384 * 100)',
        type: 2 /* Int16 */,
        permission: 'r',
    }),
    engine3PropLever: new offset_1.Offset({
        value: 0x9BE,
        name: 'engine3PropLever',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 prop lever - percent - negative = reverse',
        convert: 'Math.round({VAL} < 0 ? {VAL} / 4096 * 100 : {VAL} / 16384 * 100)',
        type: 2 /* Int16 */,
        permission: 'rw',
    }),
    engine3MixtureLever: new offset_1.Offset({
        value: 0x9C0,
        name: 'engine3MixtureLever',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 prop lever - percent',
        convert: '{VAL} / 16384 * 100',
        type: 2 /* Int16 */,
        permission: 'rw',
    }),
    engine3StarterSwitchPosition: new offset_1.Offset({
        value: 0x9C2,
        name: 'engine3StarterSwitchPosition',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 start switch position - JET: 0=off 1=start 2=gen/alt - PROP: 0=off 1=right 2=left 3=both 4=start',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    engine3Firing: new offset_1.Offset({
        value: 0x9C4,
        name: 'engine3Firing',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 combustion',
        convert: '!!{VAL}',
        type: 5 /* UInt16 */,
        permission: 'r',
    }),
    engine3N2: new offset_1.Offset({
        value: 0x9C6,
        name: 'engine3N2',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 N2 - also helo RPM %',
        convert: '{VAL} / 16384 * 100',
        type: 2 /* Int16 */,
        permission: 'rw',
    }),
    engine3N1: new offset_1.Offset({
        value: 0x9C8,
        name: 'engine3N1',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 N1 - also helo RPM %',
        convert: '{VAL} / 16384 * 100',
        type: 2 /* Int16 */,
        permission: 'rw',
    }),
    engine3PropRPM: new offset_1.Offset({
        value: 0x9C8,
        name: 'engine3PropRPM',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'derive RPM by multiplying by  - negative = counter-rotating propeller',
        convert: '{VAL} / 16384 / 65536',
        type: 2 /* Int16 */,
        permission: 'rw',
    }),
    engine3ThrottleLeverControl: new offset_1.Offset({
        value: 0x9CA,
        name: 'engine3ThrottleLeverControl',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 throttle lever control - -4096 to +16384',
        type: 2 /* Int16 */,
        permission: 'rw',
    }),
    engine3FuelFlowLbHourSSL: new offset_1.Offset({
        value: 0x9D0,
        name: 'engine3FuelFlowLbHourSSL',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 fuel flow (lb per hour, sea level)',
        convert: '{VAL} / 128',
        type: 5 /* UInt16 */,
        permission: 'r',
    }),
    engine3AntiIce: new offset_1.Offset({
        value: 0x9E2,
        name: 'engine3AntiIce',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 anti-ice/carb heat active',
        convert: '!!{VAL}',
        type: 5 /* UInt16 */,
        permission: 'r',
    }),
    engine3OilTemp: new offset_1.Offset({
        value: 0x9E8,
        name: 'engine3OilTemp',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 oil temp - celsius',
        convert: 'Math.round({VAL} * 140 / 16384)',
        type: 2 /* Int16 */,
        permission: 'r',
    }),
    engine3OilPres: new offset_1.Offset({
        value: 0x9EA,
        name: 'engine3OilPres',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 oil pressure - PSI',
        convert: 'Math.round({VAL} * 55 / 16384)',
        type: 5 /* UInt16 */,
        permission: 'r',
    }),
    engine3PressureRatio: new offset_1.Offset({
        value: 0x9EC,
        name: 'engine3PressureRatio',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 pressure ratio',
        convert: '{VAL} * 1.6 / 16384',
        type: 2 /* Int16 */,
        permission: 'r',
    }),
    engine3EGT: new offset_1.Offset({
        value: 0x9EE,
        name: 'engine3EGT',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 exhaust gas temperature - Trust only on jet engine - celsius',
        convert: 'Math.round({VAL} * 860 / 16384)',
        type: 2 /* Int16 */,
        permission: 'r',
    }),
    engine3MP: new offset_1.Offset({
        value: 0x9F0,
        name: 'engine3MP',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 manifold pressure - inHg',
        convert: '{VAL} / 1024',
        type: 5 /* UInt16 */,
        permission: 'r',
    }),
    engine3RPMScaler: new offset_1.Offset({
        value: 0x9F8,
        name: 'engine3RPMScaler',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 RPM Scaler - props: used to calculate RPM',
        type: 2 /* Int16 */,
        permission: 'r',
    }),
    engine3OilQuantity: new offset_1.Offset({
        value: 0xA00,
        name: 'engine3OilQuantity',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 oil quantity - percent',
        convert: 'Math.round({VAL} / 16384 * 100)',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    engine3Vibration: new offset_1.Offset({
        value: 0xA04,
        name: 'engine3Vibration',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 vibration',
        convert: 'Math.round({VAL} * 5 / 16384)',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    engine3HydPres: new offset_1.Offset({
        value: 0xA08,
        name: 'engine3HydPres',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 hydraulic pressure - PSI',
        convert: '{VAL} / 4',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    engine3HydQuantity: new offset_1.Offset({
        value: 0xA0C,
        name: 'engine3HydQuantity',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 hydraulic quantity - percent',
        convert: '{VAL} / 16384 * 100',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    engine3CHT: new offset_1.Offset({
        value: 0xA18,
        name: 'engine3CHT',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 cylinder head temperature - F',
        type: 8 /* Double */,
        permission: 'r',
    }),
    engine3ITT: new offset_1.Offset({
        value: 0xA20,
        name: 'engine3ITT',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 turbine temperature - C',
        convert: '{VAL} / 16384',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    engine3Torque: new offset_1.Offset({
        value: 0xA24,
        name: 'engine3Torque',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 torque - trust only for helo - percent',
        convert: '{VAL} / 16384 * 100',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    engine3FuelPres: new offset_1.Offset({
        value: 0xA28,
        name: 'engine3FuelPres',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 fuel pressure - PSI',
        convert: '{VAL} / 144',
        type: 3 /* Int32 */,
        permission: 'r',
    }),
    engine3FuelUsedSinceStart: new offset_1.Offset({
        value: 0xA3C,
        name: 'engine3FuelUsedSinceStart',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 used fuel since start - lb',
        type: 9 /* Single */,
        permission: 'r',
    }),
    engine3FuelElapsedTime: new offset_1.Offset({
        value: 0xA40,
        name: 'engine3FuelElapsedTime',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 fuel elapsed time - h',
        type: 9 /* Single */,
        permission: 'r',
    }),
    engine3FuelFlowLbHour: new offset_1.Offset({
        value: 0xA48,
        name: 'engine3FuelFlowLbHour',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 fuel elapsed time - lb/h',
        type: 8 /* Double */,
        permission: 'r',
    }),
    engine3TorqueFtLb: new offset_1.Offset({
        value: 0xA50,
        name: 'engine3TorqueFtLb',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine3 fuel elapsed time - ft lb',
        type: 9 /* Single */,
        permission: 'r',
    }),
    engine3TurbineN1: new offset_1.Offset({
        value: 0x2200,
        name: 'engine3TurbineN1',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine N1 - percent',
        type: 8 /* Double */,
        permission: 'r',
    }),
    engine3TurbineN2: new offset_1.Offset({
        value: 0x2208,
        name: 'engine3TurbineN2',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine N2 - percent',
        type: 8 /* Double */,
        permission: 'r',
    }),
    engine3TurbineCorrectedN1: new offset_1.Offset({
        value: 0x2210,
        name: 'engine3TurbineCorrectedN1',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine corrected N1 - percent',
        type: 8 /* Double */,
        permission: 'r',
    }),
    engine3TurbineCorrectedN2: new offset_1.Offset({
        value: 0x2218,
        name: 'engine3TurbineCorrectedN2',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine corrected N2 - percent',
        type: 8 /* Double */,
        permission: 'r',
    }),
    engine3TurbineCorrectedFuelFlow: new offset_1.Offset({
        value: 0x2220,
        name: 'engine3TurbineCorrectedFuelFlow',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine corrected fuel flow - lb/h',
        type: 8 /* Double */,
        permission: 'r',
    }),
    engine3TurbineTorque: new offset_1.Offset({
        value: 0x2228,
        name: 'engine3TurbineTorque',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine corrected fuel flow - 0.0 to 1.0',
        type: 8 /* Double */,
        permission: 'r',
    }),
    engine3TurbineEPR: new offset_1.Offset({
        value: 0x2230,
        name: 'engine3TurbineEPR',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine EPR',
        type: 8 /* Double */,
        permission: 'r',
    }),
    engine3TurbineITT: new offset_1.Offset({
        value: 0x2238,
        name: 'engine3TurbineITT',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine ITT',
        type: 8 /* Double */,
        permission: 'r',
    }),
    engine3TurbineAfterburnerActive: new offset_1.Offset({
        value: 0x2248,
        name: 'engine3TurbineAfterburnerActive',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine afterburner active',
        convert: '!!{VAL}',
        type: 6 /* UInt32 */,
        permission: 'r',
    }),
    engine3TurbineJetThrust: new offset_1.Offset({
        value: 0x224C,
        name: 'engine3TurbineJetThrust',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine jet thrust',
        type: 8 /* Double */,
        permission: 'r',
    }),
    engine3TurbineTankSelector: new offset_1.Offset({
        value: 0x2254,
        name: 'engine3TurbineTankSelector',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine tank selector',
        convert: 'fuelTank',
        mapping: true,
        type: 6 /* UInt32 */,
        permission: 'r',
    }),
    engine3TurbineUsedTank: new offset_1.Offset({
        value: 0x2258,
        name: 'engine3TurbineUsedTank',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine used tank',
        type: 12 /* BitArray */,
        length: 11,
        permission: 'r',
    }),
    engine3TurbineAvailableTankCount: new offset_1.Offset({
        value: 0x225C,
        name: 'engine3TurbineAvailableTankCount',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine available tank count',
        type: 6 /* UInt32 */,
        permission: 'r',
    }),
    engine3TurbineFuelFlow: new offset_1.Offset({
        value: 0x2260,
        name: 'engine3TurbineFuelFlow',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine fuel flow',
        type: 8 /* Double */,
        permission: 'r',
    }),
    engine3TurbineIsFuelAvailable: new offset_1.Offset({
        value: 0x2268,
        name: 'engine3TurbineIsFuelAvailable',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine is fuel available flag',
        convert: '!!{VAL}',
        type: 6 /* UInt32 */,
        permission: 'r',
    }),
    engine3TurbineBleedPressure: new offset_1.Offset({
        value: 0x226C,
        name: 'engine3TurbineBleedPressure',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine bleed air pressure - lb/sq in',
        type: 8 /* Double */,
        permission: 'r',
    }),
    engine3TurbineReverser: new offset_1.Offset({
        value: 0x227C,
        name: 'engine3TurbineReverser',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine reverser position - 0.0 - 1.0 lb/sq in',
        convert: 'Math.round(+(+({VAL}).toFixed(4) * 100).toFixed(2))',
        type: 8 /* Double */,
        permission: 'r',
    }),
    engine3TurbineVibration: new offset_1.Offset({
        value: 0x2284,
        name: 'engine3TurbineVibration',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine vibration',
        type: 8 /* Double */,
        permission: 'r',
    }),
    engine3TurbineIgnition: new offset_1.Offset({
        value: 0x228C,
        name: 'engine3TurbineIgnition',
        category: offset_category_1.OffsetCategory.ENGINE,
        description: 'engine 3 turbine is fuel available flag',
        convert: '!!{VAL}',
        type: 6 /* UInt32 */,
        permission: 'rw',
    }),
};
