"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const offset_1 = require("./../../../../shared/offset");
const offset_category_1 = require("./../../../../shared/offset-category");
exports.weatherSettings = {
    upperCloudCeilingSetting: new offset_1.Offset({
        value: 0xF1C,
        name: 'upperCloudCeilingSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'upper cloud layer ceiling - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    upperCloudBaseSetting: new offset_1.Offset({
        value: 0xF1E,
        name: 'upperCloudBaseSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'upper cloud layer base - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    upperCloudCoverageSetting: new offset_1.Offset({
        value: 0xF20,
        name: 'upperCloudCoverageSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'upper cloud layer coverage - oktas - setting',
        convert: 'Math.round(({VAL} + 1) / 8192)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    upperCloudVariationSetting: new offset_1.Offset({
        value: 0xF22,
        name: 'upperCloudVariationSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'upper cloud layer variation - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    lowerCloudCeilingSetting: new offset_1.Offset({
        value: 0xF24,
        name: 'lowerCloudCeilingSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'lower cloud layer ceiling - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    lowerCloudBaseSetting: new offset_1.Offset({
        value: 0xF26,
        name: 'lowerCloudBaseSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'lower cloud layer base - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    lowerCloudCoverageSetting: new offset_1.Offset({
        value: 0xF28,
        name: 'lowerCloudCoverageSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'lower cloud layer coverage - oktas - setting',
        convert: 'Math.round(({VAL} + 1) / 8192)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    lowerCloudVariationSetting: new offset_1.Offset({
        value: 0xF2A,
        name: 'lowerCloudVariationSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'lower cloud layer variation - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    stormCloudCeilingSetting: new offset_1.Offset({
        value: 0xF2C,
        name: 'stormCloudCeilingSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'storm cloud layer ceiling - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    stormCloudBaseSetting: new offset_1.Offset({
        value: 0xF2E,
        name: 'stormCloudBaseSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'storm cloud layer base - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    stormCloudCoverageSetting: new offset_1.Offset({
        value: 0xF30,
        name: 'stormCloudCoverageSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'storm cloud layer coverage - oktas - setting',
        convert: 'Math.round(({VAL} + 1) / 8192)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    stormCloudVariationSetting: new offset_1.Offset({
        value: 0xF32,
        name: 'stormCloudVariationSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'storm cloud layer variation - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    upperTemperatureLevelSetting: new offset_1.Offset({
        value: 0xF34,
        name: 'upperTemperatureLevelSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'upper temperature level - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    upperTemperatureSetting: new offset_1.Offset({
        value: 0xF36,
        name: 'upperTemperatureSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'upper temperature - degrees C - setting',
        convert: 'Math.round({VAL} / 256)',
        type: 2 /* Int16 */,
        permission: 'rw',
    }),
    middleTemperatureLevelSetting: new offset_1.Offset({
        value: 0xF38,
        name: 'middleTemperatureLevelSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'middle temperature level - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    middleTemperatureSetting: new offset_1.Offset({
        value: 0xF3A,
        name: 'middleTemperatureSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'middle temperature - degrees C - setting',
        convert: 'Math.round({VAL} / 256)',
        type: 2 /* Int16 */,
        permission: 'rw',
    }),
    lowerTemperatureLevelSetting: new offset_1.Offset({
        value: 0xF3C,
        name: 'lowerTemperatureLevelSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'lower temperature level - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    lowerTemperatureSetting: new offset_1.Offset({
        value: 0xF3E,
        name: 'lowerTemperatureSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'lower temperature - degrees C - setting',
        convert: 'Math.round({VAL} / 256)',
        type: 2 /* Int16 */,
        permission: 'rw',
    }),
    surfaceTemperatureLevelSetting: new offset_1.Offset({
        value: 0xF40,
        name: 'surfaceTemperatureLevelSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'surface temperature level - ground elevation  - setting- ft',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    surfaceTemperatureSetting: new offset_1.Offset({
        value: 0xF42,
        name: 'surfaceTemperatureSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'surface temperature - degrees C - setting',
        convert: 'Math.round({VAL} / 256)',
        type: 2 /* Int16 */,
        permission: 'rw',
    }),
    temperatureDriftSetting: new offset_1.Offset({
        value: 0xF44,
        name: 'temperatureDriftSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'temperature drift - degrees C - setting',
        convert: 'Math.round({VAL} / 256)',
        type: 2 /* Int16 */,
        permission: 'rw',
    }),
    temperatureDayNightVariationSetting: new offset_1.Offset({
        value: 0xF46,
        name: 'temperatureDayNightVariationSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'temperature day night variation - degrees C - setting',
        convert: 'Math.round({VAL} / 256)',
        type: 2 /* Int16 */,
        permission: 'rw',
    }),
    pressureQNHSetting: new offset_1.Offset({
        value: 0xF48,
        name: 'pressureQNHSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'pressure QNH - mb - setting',
        convert: 'Math.round({VAL} / 16)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    pressureDriftSetting: new offset_1.Offset({
        value: 0xF4A,
        name: 'pressureDriftSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'pressure drift - mb - setting',
        convert: 'Math.round({VAL} / 16)',
        type: 2 /* Int16 */,
        permission: 'rw',
    }),
    upperWindCeilingSetting: new offset_1.Offset({
        value: 0xF4C,
        name: 'upperWindCeilingSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'upper wind ceiling - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    upperWindBaseSetting: new offset_1.Offset({
        value: 0xF4E,
        name: 'upperWindBaseSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'upper wind ceiling - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    upperWindSpeedSetting: new offset_1.Offset({
        value: 0xF50,
        name: 'upperWindSpeedSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'upper wind ceiling - kt - setting',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    upperWindDirectionSetting: new offset_1.Offset({
        value: 0xF52,
        name: 'upperWindDirectionSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'upper wind ceiling - TRUE degrees - setting',
        convert: '+({VAL} * 360 / 65536).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    upperWindTurbulenceSetting: new offset_1.Offset({
        value: 0xF54,
        name: 'upperWindTurbulenceSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'upper wind turbulence - 0-255 - setting',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    upperWindGustEnabledSetting: new offset_1.Offset({
        value: 0xF56,
        name: 'upperWindGustEnabledSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'upper wind gust enabled - setting',
        convert: '!!{VAL}',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    middleWindCeilingSetting: new offset_1.Offset({
        value: 0xF58,
        name: 'middleWindCeilingSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'middle wind ceiling - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    middleWindBaseSetting: new offset_1.Offset({
        value: 0xF5A,
        name: 'middleWindBaseSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'middle wind ceiling - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    middleWindSpeedSetting: new offset_1.Offset({
        value: 0xF5C,
        name: 'middleWindSpeedSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'middle wind ceiling - kt - setting',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    middleWindDirectionSetting: new offset_1.Offset({
        value: 0xF5E,
        name: 'middleWindDirectionSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'middle wind ceiling - TRUE degrees - setting',
        convert: '+({VAL} * 360 / 65536).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    middleWindTurbulenceSetting: new offset_1.Offset({
        value: 0xF60,
        name: 'middleWindTurbulenceSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'middle wind turbulence - 0-255 - setting',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    middleWindGustEnabledSetting: new offset_1.Offset({
        value: 0xF62,
        name: 'middleWindGustEnabledSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'middle wind gust enabled - setting',
        convert: '!!{VAL}',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    lowerWindCeilingSetting: new offset_1.Offset({
        value: 0xF64,
        name: 'lowerWindCeilingSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'lower wind ceiling - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    lowerWindBaseSetting: new offset_1.Offset({
        value: 0xF66,
        name: 'lowerWindBaseSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'lower wind ceiling - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    lowerWindSpeedSetting: new offset_1.Offset({
        value: 0xF68,
        name: 'lowerWindSpeedSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'lower wind ceiling - kt - setting',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    lowerWindDirectionSetting: new offset_1.Offset({
        value: 0xF6A,
        name: 'lowerWindDirectionSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'lower wind ceiling - TRUE degrees - setting',
        convert: '+({VAL} * 360 / 65536).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    lowerWindTurbulenceSetting: new offset_1.Offset({
        value: 0xF6C,
        name: 'lowerWindTurbulenceSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'lower wind turbulence - 0-255 - setting',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    lowerWindGustEnabledSetting: new offset_1.Offset({
        value: 0xF6E,
        name: 'lowerWindGustEnabledSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'lower wind gust enabled - setting',
        convert: '!!{VAL}',
        type: 2 /* Int16 */,
        permission: 'rw',
    }),
    surfaceWindCeilingSetting: new offset_1.Offset({
        value: 0xF70,
        name: 'surfaceWindCeilingSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'surface wind ceiling - ft - setting',
        convert: '+({VAL} * 3.28084).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    surfaceWindSpeedSetting: new offset_1.Offset({
        value: 0xF72,
        name: 'surfaceWindSpeedSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'surface wind speed - kt - settings',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    surfaceWindDirectionSetting: new offset_1.Offset({
        value: 0xF74,
        name: 'surfaceWindSpeedSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'surface wind direction - MAG degrees - settings',
        convert: '+({VAL} * 360 / 65536).toFixed(2)',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    surfaceWindTurbulenceSetting: new offset_1.Offset({
        value: 0xF76,
        name: 'surfaceWindTurbulenceSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'surface wind turbulence - 0-255 - setting',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    surfaceWindGustEnabledSetting: new offset_1.Offset({
        value: 0xF78,
        name: 'surfaceWindGustEnabledSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'surface wind gust enabled - setting',
        convert: '!!{VAL}',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    upperCloudTypeSetting: new offset_1.Offset({
        value: 0xF7A,
        name: 'upperCloudTypeSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'upper cloud type - setting',
        convert: 'cloudType',
        mapping: true,
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    upperCloudIcingSetting: new offset_1.Offset({
        value: 0xF7C,
        name: 'upperCloudIcingSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'upper cloud icing - setting',
        convert: '!!{VAL}',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    upperCloudTurbulenceSetting: new offset_1.Offset({
        value: 0xF7E,
        name: 'upperCloudTurbulenceSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'upper cloud turbulence - 0-255 - setting',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    lowerCloudTypeSetting: new offset_1.Offset({
        value: 0xF80,
        name: 'lowerCloudTypeSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'lower cloud type - setting',
        convert: 'cloudType',
        mapping: true,
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    lowerCloudIcingSetting: new offset_1.Offset({
        value: 0xF82,
        name: 'lowerCloudIcingSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'lower cloud icing - setting',
        convert: '!!{VAL}',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    lowerCloudTurbulenceSetting: new offset_1.Offset({
        value: 0xF84,
        name: 'lowerCloudTurbulenceSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'lower cloud turbulence - 0-255 - setting',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    stormCloudTypeSetting: new offset_1.Offset({
        value: 0xF86,
        name: 'stormCloudTypeSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'storm cloud type - setting',
        convert: 'cloudType',
        mapping: true,
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    stormCloudIcingSetting: new offset_1.Offset({
        value: 0xF88,
        name: 'stormCloudIcingSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'storm cloud icing - setting',
        convert: '!!{VAL}',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    stormCloudTurbulenceSetting: new offset_1.Offset({
        value: 0xF8A,
        name: 'stormCloudTurbulenceSetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'storm cloud turbulence - 0-255 - setting',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
    visibilitySetting: new offset_1.Offset({
        value: 0xF8C,
        name: 'visibilitySetting',
        category: offset_category_1.OffsetCategory.WEATHER,
        description: 'visibility setting - sm',
        convert: '{VAL} / 100',
        type: 5 /* UInt16 */,
        permission: 'rw',
    }),
};
